config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'dashboard/status', defaults: {format: :json}
  root to: 'dashboard#index'

  resources :tasks do
    member do
      get 'change_status'
    end
  end
  resources :projects

  # Devise routers
  devise_for :users
end

app/models/project.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: projects
#
#  id          :bigint           not null, primary key
#  description :string
#  name        :string
#  slug        :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

# app/models/project.rb
class Project < ApplicationRecord
  include Sluggable

  has_many :tasks, dependent: :nullify

  validates :name, :description, presence: true

  ransacker :id_to_s do
    Arel.sql("regexp_replace(to_char(\"#{table_name}\".\"id\", '9999999'), ' ', '', 'g')")
  end

  # Search by id, name or description
  ransack_alias :search, :id_to_s_or_name_or_description

  def review_tasks
    tasks.map(&:completed?)
  end

  def waiting_tasks
    tasks.map(&:completed?)
  end

  def completed_tasks
    tasks.map(&:completed?)
  end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[show edit update destroy]

  # GET /projects
  def index
    @query = Project.ransack(params[:q])
    @pagy, @projects = pagy(@query.result, page: params[:page])
  end

  # GET /projects/1
  def show; end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit; end

  # POST /projects
  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.friendly.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def project_params
    params.require(:project).permit(:name, :description)
  end
end

app/views/projects/_form.html.erb
<%= simple_form_for(@project, html: {id: 'form_project'}) do |f| %>
  <% content_for :body do %>
    <%= f.input :name, wrapper_html: {class: 'col-lg-3 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
    <%= f.input :description, wrapper_html: {class: 'col-lg-9 col-sm-12'}, input_html: {disabled: show?(f.object.persisted?)} %>
  <% end %>
  <%= render template: 'application/form', locals: {form: @project} %>
<% end %>

app/views/projects/edit.html.erb
<%= render 'form', form: @project %>

app/views/projects/index.html.erb
<%= render 'application/page_header', model: Project %>
<div class="card">
  <div class="card-status bg-blue"></div>
  <div class="card-header p-4">
    <div class="col-sm-12 col-lg-12">
      <div class="form-row">
        <div class="col-sm-12 col-lg-6 p-0">
          <%= render 'application/pagy_count', list: @pagy %>
        </div>
        <div class="col-sm-12 col-lg-6 p-0">
          <%= search_form_for @query do |f| %>
            <%= f.search_field :search_cont, class: 'form-control', placeholder: t('helpers.search') %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-body table-responsive p-0 m-0">
    <table class="table card-table table-vcenter text-nowrap table-hover">
      <thead>
      <tr>
        <th class="w-1">#</th>
        <th><%= Project.human_attribute_name :name %></th>
        <th><%= t('helpers.labels.actions') %></th>
      </tr>
      </thead>
      <tbody>
      <% @projects.each do |project| %>
        <tr>
          <td class="text-muted"><%= project.id %></td>
          <td><%= project.name %></td>
          <td class="text-center">
            <%= render 'application/table_links', f: project %>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <div class="card-footer">
    <%= render 'application/footer_links', url: new_project_path, model: Project %>
  </div>
</div>

app/views/projects/new.html.erb
<%= render 'form', form: @project %>

app/views/projects/show.html.erb
<%= render 'form', form: @project %>