config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'dashboard/status', defaults: {format: :json}
  root to: 'dashboard#index'

  resources :tasks do
    member do
      get 'change_status'
    end
  end
  resources :projects

  # Devise routers
  devise_for :users
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include Pagy::Backend

  before_action :authenticate_user!
  before_action :set_referrer

  # Handle authorization exception according to request format
  rescue_from CanCan::AccessDenied do |_exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'application/json' }
      format.html do
        redirect_to send(@referrer), flash: { error: 'Forbidden' }
      end
      format.js { head :forbidden, content_type: 'text/html' }
    end
  end

  # Dashboard page
  def index; end

  private

  # Set previous referrer URL to the redirect_to method
  def set_referrer
    @referrer = "#{request.referer.presence || 'root'}_path"
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

require 'pagy/extras/bootstrap'

module ApplicationHelper
  include Pagy::Frontend

  def show?(form)
    form && action_name == 'show'
  end

  def active_action?(controller)
    'active' if controller.remove('/') == controller_name
  end

  def asset_exist?(path)
    File.exist?(Rails.application
      .root.join('app', 'javascript', 'packs', "#{path}.js"))
  end

  def flashes
    flash.to_hash.slice('alert', 'error', 'notice', 'success')
  end

  def alert_type(flash_type)
    case flash_type
    when 'alert'
      'warning'
    when 'error'
      'danger'
    when 'notice'
      'success'
    when 'success'
      'success'
    else
      'success'
    end
  end

  def status_type(status)
    case status
    when 'review'
      'primary'
    when 'waiting'
      'default'
    when 'completed'
      'success'
    else
      'default'
    end
  end

  def alert_icon(flash_type)
    case flash_type
    when 'alert' || 'error'
      'fas fa-exclamation-triangle'
    when 'notice'
      'fas fa-check'
    when 'success'
      'fas fa-check'
    else
      'fas fa-exclamation-circle'
    end
  end
end

app/views/application/_app.html.erb
<div class="page">
  <div class="flex-fill">
    <%= render 'application/navbar' %>
    <%= render 'application/menu' %>
    <div class="my-5 my-md-5">
      <div class="container">
        <%= render 'application/flashes' %>
        <%= yield :page_header %>
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/application/_chart.html.erb
<div class="card mb-3">
  <div class="card-header border-bottom-0">
    <h3 class="card-title font-weight-bold">
      <%= title %>
    </h3>
    <div class="card-options">
      <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
    </div>
  </div>
  <div class="card-body">
    <div id="dimmer_<%= id %>" class="dimmer">
      <div class="row mb-5">
        <div id="loader_<%= id %>"></div>
      </div>
      <div class="dimmer-content">
        <div id="<%= id %>"></div>
      </div>
    </div>
  </div>
</div>

app/views/application/_dashboard_card.html.erb
<div class="col-md col-sm-3 col-lg">
  <div class="card bg-<%= color ||= 'white' %>">
    <div class="card-body p-3 m-0 text-center">
      <div class="row">
        <div class="col-4 col-sm-12 text-sm-center">
          <i class="<%= icon ||= 'fas fa-cube' %> fa-2x p-4 py-auto align-middle"></i>
        </div>
        <div class="col-8 col-sm-12 text-right align-content-center align-middle text-sm-center">
          <div class="h3 font-weight-bold">
            <%= link_to action do %>
              <%= description %>
            <% end %>
          </div>
          <div id="<%= id %>" class="h3 m-0"><%= value ||= 0 %></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_devise.html.erb
<div class="page">
  <div class="container">
    <div class="row">
      <div class="col col-login px-0 mx-auto">
        <div class="text-center mb-6">
          <%= image_tag 'logo.png', class: 'h-8', alt: 'logo' %>
          <h1 class="page-title font-weight-bold">Conviso App</h1>
        </div>
        <%= yield %>
      </div>
    </div>
  </div>
</div>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <% flashes.each do |key, value| -%>
    <div class="alert alert-<%= alert_type key %> alert-dismissible p-4 mb-3" role="alert">
      <span class="float-right" role="button" data-dismiss="alert">
        <i class="fas fa-times"></i>
      </span>
      <i class="<%= "#{alert_icon key}" %>"></i> &nbsp;<%= value %>
    </div>
  <% end -%>
<% end %>

app/views/application/_footer_links.html.erb
<div class="col-sm-12 col-lg-12 p-0">
  <div class="form-row">
    <% if can? :create, model %>
      <div class="col-sm-12 col-lg-6 p-0">
        <%= link_to url, class: 'btn btn-primary align-middle mb-md-0 mb-sm-3' do %>
          <i class="fas fa-plus mr-2"></i>Novo
        <% end %>
      </div>
    <% end %>
    <% if @pagy.count > 1 %>
      <div class="col-sm-12 col-lg-<%= can?(:create, model) ? '6' : '12' %>">
        <div class="float-right">
          <%= pagy_bootstrap_combo_nav_js(@pagy).html_safe %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/application/_form_buttons.html.erb
<div class="btn-list">
  <% if action_name == 'show' %>
    <%= link_to send("edit_#{f.model_name.singular}_path"), class: 'btn btn-primary', role: 'button' do %>
      <i class="fas fa-edit mr-2"></i><span class="btn-title"><%= t 'helpers.submit.edit' %></span>
    <% end %>
    <%= link_to send("new_#{f.model_name.singular}_path"), class: 'btn btn-info btn-info', role: 'button' do %>
      <i class="fas fa-plus mr-2"></i><span class="btn-title"><%= t 'helpers.submit.new' %></span>
    <% end %>
  <% else %>
    <%= button_tag class: 'btn btn-primary btn-submit',
                   data: {disable_with: '<i class="fas fa-spinner fa-spin"></i>Salvando...'.html_safe} do %>
      <i class="fas fa-save mr-2"></i><span class="btn-title"><%= t("helpers.submit.#{action_name == 'new' ? 'create' : 'update'}") %></span>
    <% end %>
  <% end %>
  <%= link_to send("#{f.model_name.plural}_path"),
              class: 'btn btn-danger btn-cancel', role: 'button' do %>
    <i class="fa fa-undo mr-2"></i><span class="btn-title"><%= t 'helpers.submit.cancel' %></span>
  <% end %>
</div>

app/views/application/_menu.html.erb
<nav class="header collapse d-lg-flex p-0" id="menu">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-3 ml-auto"></div>
      <div class="col-lg order-lg-first">
        <ul class="nav nav-tabs border-0 flex-column flex-lg-row">
          <li class="nav-item">
            <%= link_to root_path, class: "nav-link link #{'active' if controller_name == 'dashboard'}" do %>
              <i class="fas fa-chart-line mr-2"></i>Dashboard
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to projects_path, class: "nav-link link #{active_action? projects_path}" do %>
              <i class="fas fa-project-diagram mr-2"></i><%= Project.model_name.human(count: 2) %>
            <% end %>
          </li>
          <li class="nav-item">
            <%= link_to tasks_path, class: "nav-link link #{active_action? tasks_path}" do %>
              <i class="fas fa-tasks mr-2"></i><%= Task.model_name.human(count: 2) %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/application/_navbar.html.erb
<div class="header py-4">
  <div class="container">
    <div class="d-flex">
      <%= link_to root_path, class: 'header-brand text-blue-deep' do %>
        <%= image_tag 'logo.png', class: 'header-brand-img mr-2', alt: 'image' %><%= ENV['APP_NAME'] ||= 'AppName' %>
      <% end %>
      <div class="d-flex order-lg-2 ml-auto">
        <div class="dropdown">
          <div class="nav-link pr-0 leading-none" data-toggle="dropdown">
            <span class="avatar text-white">
              <%= image_tag 'https://i.pravatar.cc/300', class: 'rounded-circle' %>
            </span>
            <span class="ml-2 d-none d-lg-block">
              <span class="text-blue-deep font-weight-bold"><%= current_user.email %></span>
              <small class="text-muted d-block mt-1">Administrator</small>
            </span>
          </div>
          <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
            <%= link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do %>
              <i class="fas fa-sign-out-alt dropdown-icon"></i> Logout
            <% end %>
          </div>
        </div>
      </div>
      <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse" data-target="#menu">
        <span class="header-toggler-icon"></span>
      </a>
    </div>
  </div>
</div>

app/views/application/_pagy_count.html.erb
<% if list.present? %>
  <h1 class="pt-2 card-title mb-2">
    <% if list.count.zero? %>
      Nenhum registro encontrado
    <% elsif list.count > 1 %>
      <strong class="mr-1"><%= list.count %></strong>registros encontrados
    <% else %>
      <strong class="mr-1"><%= list.count %></strong>registro encontrado
    <% end %>
  </h1>
<% end %>

app/views/application/_project_card.html.erb
<div class="accordion" id="accordion">
  <% projects.each do |project| %>
    <div class="card mb-2 card-project">
      <div class="card-header" id="head<%= project.id %>">
        <a class="btn btn-link d-block px-0" role="button" data-toggle="collapse"
           data-target="#collapse<%= project.id %>"
           aria-expanded="true" aria-controls="collapse<%= project.id %>">
          <h2 class="card-title font-weight-bold">
            <%= "##{project.id.to_s.rjust(8, '0')} - #{project.name}" %>
          </h2>
        </a>
      </div>
      <div id="collapse<%= project.id %>" class="collapse show"
           aria-labelledby="head<%= project.id %>" data-parent="#accordion">
        <div class="card-body">
          <ul id="project-task-<%= project.id %>" class="project-task sortable list-unstyled list-separated content">
            <% project.tasks.each do |task| %>
              <%= render 'application/task_card', task: task %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/application/_table_links.html.erb
<%= link_to f, class: 'btn btn-icon bg-transparent text-blue-deep mr-1', role: 'button' do %>
  <i class="far fa-eye p-0"></i>
<% end %>
<% if can? :update, f.model_name.singular.camelize.constantize %>
  <%= link_to send("edit_#{f.model_name.singular}_path", f),
              class: 'btn btn-icon bg-transparent text-blue-deep mr-1', role: 'button' do %>
    <i class="fas fa-edit p-0"></i>
  <% end %>
<% end %>
<% if can? :destroy, f.model_name.singular.camelize.constantize %>
  <%= link_to f, class: 'btn btn-icon bg-transparent text-blue-deep', method: :delete,
              data: {confirm: "Confirma a remoção do registro de código ##{f.id}?"},
              role: 'button', id: 'btn-remove', title: t('helpers.submit.delete') do %>
    <i class="fas fa-trash p-0"></i>
  <% end %>
<% end %>

app/views/application/form.html.erb
<%= render 'application/page_header', model: form %>
<div class="card">
  <div class="card-status <%= form.errors.any? ? 'bg-red' : 'bg-blue' %>"></div>
  <div class="card-body pb-3">
    <div class="dimmer">
      <div class="dimmer-content">
        <div class="form-row">
          <%= yield :body %>
        </div>
      </div>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col">
        <div class="float-left">
          <%= render 'application/form_buttons', f: form %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/form_devise.html.erb
<%= render 'application/page_header', model: form %>
<div class="card">
  <div class="card-status <%= form.errors.any? ? 'bg-red' : 'bg-blue' %>"></div>
  <div class="card-header">
    <h1 class="card-title">
      <%= "#{form.model_name.human} ##{form.id}" %>
    </h1>
  </div>
  <div class="card-body <%= 'pt-0 pb-0' if (tabs ||= nil) %>">
    <div class="form-row">
      <%= yield :body %>
    </div>
  </div>
  <div class="card-footer">
    <div class="row">
      <div class="col">
        <div class="float-left">
          <div class="btn-list">
            <%= button_tag class: 'btn btn-primary btn-submit',
                           data: {disable_with: '<i class="fas fa-spinner fa-spin"></i>Salvando...'.html_safe} do %>
              <i class="fas fa-save mr-2"></i><span class="btn-title"><%= t 'helpers.submit.create' %></span>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>